# -*- coding: utf-8 -*-
"""PalmerPenguinsM1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpftCDdyCaGYrdy1StEyncQpJ-WsZxhA
"""

# PalmerPenguins.py
# D. Singletary
# 8/6/2026
# Introduces the Palmer Penguin species

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

# output the species names with introductory text
print("Introducing the Palmer Penguins:")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()
print("There are a total of " +
      str(TOTAL_SPECIES) +
      " penguin species in this dataset.")